### ISSUE TITLE
Ustalenie terminu spotkania zespołu

### ISSUE THREAD

**Issue by s-nez** [mnatan/CHARON#2]
Trzeba się w końcu spotkać, żeby ustalić kto się czym zajmie i jakiś zarys czasowy pierwszej fazy projektu. Biorąc pod uwagę zajętość członków zespołu, proponuję wideokonferencję (oczywiście, gdyby się udało znaleźć termin na fizyczne spotkanie, to byłoby lepiej).

Propozycje terminów i komentarze do nich zamieszczamy w tym issue do **07.01.2016 23:59:59**.

**Comment by mnatan** [comment]
Proponuję:
**Piątek 8.01.2016, 18:00**

Dodatkowo - Szymon proponuje spoko wideokonferencję do której wystarczy przeglądarka :+1:

**Comment by s-nez** [comment]
>  Piątek 8.01.2016, 18:00

Mi ten termin pasuje.

**Comment by s-nez** [comment]
Termin zgłaszania propozycji minął. Spotkanie odbędzie się **8.01.2016 o18:00** na https://opentokrtc.com/hueislovehueislifemahconference.
